# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/ITCar_Camera

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/ITCar_Camera

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/ITCar_Camera/CMakeFiles /home/ubuntu/ITCar_Camera/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/ITCar_Camera/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named autocar

# Build rule for target.
autocar: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 autocar
.PHONY : autocar

# fast build rule for target.
autocar/fast:
	$(MAKE) -f CMakeFiles/autocar.dir/build.make CMakeFiles/autocar.dir/build
.PHONY : autocar/fast

src/Controller.o: src/Controller.cpp.o
.PHONY : src/Controller.o

# target to build an object file
src/Controller.cpp.o:
	$(MAKE) -f CMakeFiles/autocar.dir/build.make CMakeFiles/autocar.dir/src/Controller.cpp.o
.PHONY : src/Controller.cpp.o

src/Controller.i: src/Controller.cpp.i
.PHONY : src/Controller.i

# target to preprocess a source file
src/Controller.cpp.i:
	$(MAKE) -f CMakeFiles/autocar.dir/build.make CMakeFiles/autocar.dir/src/Controller.cpp.i
.PHONY : src/Controller.cpp.i

src/Controller.s: src/Controller.cpp.s
.PHONY : src/Controller.s

# target to generate assembly for a file
src/Controller.cpp.s:
	$(MAKE) -f CMakeFiles/autocar.dir/build.make CMakeFiles/autocar.dir/src/Controller.cpp.s
.PHONY : src/Controller.cpp.s

src/JHPWMPCA9685.o: src/JHPWMPCA9685.cpp.o
.PHONY : src/JHPWMPCA9685.o

# target to build an object file
src/JHPWMPCA9685.cpp.o:
	$(MAKE) -f CMakeFiles/autocar.dir/build.make CMakeFiles/autocar.dir/src/JHPWMPCA9685.cpp.o
.PHONY : src/JHPWMPCA9685.cpp.o

src/JHPWMPCA9685.i: src/JHPWMPCA9685.cpp.i
.PHONY : src/JHPWMPCA9685.i

# target to preprocess a source file
src/JHPWMPCA9685.cpp.i:
	$(MAKE) -f CMakeFiles/autocar.dir/build.make CMakeFiles/autocar.dir/src/JHPWMPCA9685.cpp.i
.PHONY : src/JHPWMPCA9685.cpp.i

src/JHPWMPCA9685.s: src/JHPWMPCA9685.cpp.s
.PHONY : src/JHPWMPCA9685.s

# target to generate assembly for a file
src/JHPWMPCA9685.cpp.s:
	$(MAKE) -f CMakeFiles/autocar.dir/build.make CMakeFiles/autocar.dir/src/JHPWMPCA9685.cpp.s
.PHONY : src/JHPWMPCA9685.cpp.s

src/Sign_regconize.o: src/Sign_regconize.cpp.o
.PHONY : src/Sign_regconize.o

# target to build an object file
src/Sign_regconize.cpp.o:
	$(MAKE) -f CMakeFiles/autocar.dir/build.make CMakeFiles/autocar.dir/src/Sign_regconize.cpp.o
.PHONY : src/Sign_regconize.cpp.o

src/Sign_regconize.i: src/Sign_regconize.cpp.i
.PHONY : src/Sign_regconize.i

# target to preprocess a source file
src/Sign_regconize.cpp.i:
	$(MAKE) -f CMakeFiles/autocar.dir/build.make CMakeFiles/autocar.dir/src/Sign_regconize.cpp.i
.PHONY : src/Sign_regconize.cpp.i

src/Sign_regconize.s: src/Sign_regconize.cpp.s
.PHONY : src/Sign_regconize.s

# target to generate assembly for a file
src/Sign_regconize.cpp.s:
	$(MAKE) -f CMakeFiles/autocar.dir/build.make CMakeFiles/autocar.dir/src/Sign_regconize.cpp.s
.PHONY : src/Sign_regconize.cpp.s

src/jetsonGPIO.o: src/jetsonGPIO.cpp.o
.PHONY : src/jetsonGPIO.o

# target to build an object file
src/jetsonGPIO.cpp.o:
	$(MAKE) -f CMakeFiles/autocar.dir/build.make CMakeFiles/autocar.dir/src/jetsonGPIO.cpp.o
.PHONY : src/jetsonGPIO.cpp.o

src/jetsonGPIO.i: src/jetsonGPIO.cpp.i
.PHONY : src/jetsonGPIO.i

# target to preprocess a source file
src/jetsonGPIO.cpp.i:
	$(MAKE) -f CMakeFiles/autocar.dir/build.make CMakeFiles/autocar.dir/src/jetsonGPIO.cpp.i
.PHONY : src/jetsonGPIO.cpp.i

src/jetsonGPIO.s: src/jetsonGPIO.cpp.s
.PHONY : src/jetsonGPIO.s

# target to generate assembly for a file
src/jetsonGPIO.cpp.s:
	$(MAKE) -f CMakeFiles/autocar.dir/build.make CMakeFiles/autocar.dir/src/jetsonGPIO.cpp.s
.PHONY : src/jetsonGPIO.cpp.s

src/main_autocar.o: src/main_autocar.cpp.o
.PHONY : src/main_autocar.o

# target to build an object file
src/main_autocar.cpp.o:
	$(MAKE) -f CMakeFiles/autocar.dir/build.make CMakeFiles/autocar.dir/src/main_autocar.cpp.o
.PHONY : src/main_autocar.cpp.o

src/main_autocar.i: src/main_autocar.cpp.i
.PHONY : src/main_autocar.i

# target to preprocess a source file
src/main_autocar.cpp.i:
	$(MAKE) -f CMakeFiles/autocar.dir/build.make CMakeFiles/autocar.dir/src/main_autocar.cpp.i
.PHONY : src/main_autocar.cpp.i

src/main_autocar.s: src/main_autocar.cpp.s
.PHONY : src/main_autocar.s

# target to generate assembly for a file
src/main_autocar.cpp.s:
	$(MAKE) -f CMakeFiles/autocar.dir/build.make CMakeFiles/autocar.dir/src/main_autocar.cpp.s
.PHONY : src/main_autocar.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... autocar"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/Controller.o"
	@echo "... src/Controller.i"
	@echo "... src/Controller.s"
	@echo "... src/JHPWMPCA9685.o"
	@echo "... src/JHPWMPCA9685.i"
	@echo "... src/JHPWMPCA9685.s"
	@echo "... src/Sign_regconize.o"
	@echo "... src/Sign_regconize.i"
	@echo "... src/Sign_regconize.s"
	@echo "... src/jetsonGPIO.o"
	@echo "... src/jetsonGPIO.i"
	@echo "... src/jetsonGPIO.s"
	@echo "... src/main_autocar.o"
	@echo "... src/main_autocar.i"
	@echo "... src/main_autocar.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

